# Einstellbare Variablen
use_contour = False
resize_x = 224
resize_y = 224
calibration_percent = 1.06
video_path = 'soll_zustand.avi'
min_recorded_frames = 20
contour_threshold = 5
recording_duration = 20